spring:
  application:
    name: Authorization Server With Spring/SpringBoot
  datasource:
    url: jdbc:h2:mem:authorization-server-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 9000

logging:
  level:
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
    org.springframework.data.jpa: trace
    org.springframework.orm.jpa: trace